//! THE DEPLOY GATE (notes/ledger-header.org; spec 00002 User Story 2,
//! FR-007, SC-003): a `#[derive(Ledger)]` block's `initial_state()` is a
//! state the Midnight 2.x ledger ACCEPTS as a deploy, and the state
//! compactc's generated `initialState` builds for the same fields.
//!
//! - **T4, deploy + VM.** Headed blocks of every own-field count the spec
//!   names — 0, 1, 14, 15, 16, 30, 211, 225, 226 — each with a magic-only
//!   and a multi-field standard (`ledger_deploy/blocks.rs`, GENERATED by
//!   [`regenerate_blocks`] below). Each state passes the ledger's
//!   `well_formed` and applies (`ledger_deploy/deploy.rs`), its root is
//!   `1 + R(n)` entries (sixteen at 15 and 225), its magic is at `[0]` /
//!   `[0, 0]` under exactly one `bytes<32>` atom, and circuits writing the
//!   first (a Cell write), a middle (a Counter increment) and the last (a
//!   Map insert) body field run through `QueryContext::query` against the
//!   DEPLOYED state: each write lands at exactly the rule's path, nothing
//!   else moves, and the magic is bit-identical before and after.
//! - **T9.** The multi-field standard's `version` write lands at `[0, 1]`
//!   only; `[0, 0]` does not move.
//! - **T4b, compactc's JS.** For non-headed blocks, the serialized state
//!   equals what compactc 0.34.0's generated `initialState` serializes, byte
//!   for byte (`tests/fixtures/initial_state/*.state.hex`, produced in node
//!   by project 00002's JS oracle; provenance in each file's header): one
//!   field of every ledger type (`e_adts`), the shipped `Adts` contract, and
//!   the magic-first probes of 16 and 226 fields — whose magic a Compact
//!   CONSTRUCTOR writes, reproduced here with `StateBuilder::set`.
//!
//! Also: the composite slots' shares of a headed block's state (a Signet and
//! a Pending; an Outbox), deployed.
//!
//! IT IS A TEST-ONLY SET OF BLOCKS: nothing here enters the snapshots or the
//! ZKIR dump.

#[path = "ledger_deploy/blocks.rs"]
mod blocks;
#[path = "ledger_deploy/deploy.rs"]
mod deploy;

use midnight_onchain_state::state::StateValue;
use midnight_storage::db::InMemoryDB;
use midnight_storage::storage::HashMap as StorageHashMap;
use minocrab::v3::{Circuit3, Compiled3};
use minocrab::{AlignmentAtom, Public};
use minocrab_contracts::evm_flow::{HandleOwned, Outbox, Owned, Pending};
use minocrab_contracts::signet_flow::Signet;
use minocrab_contracts::treasury::{Amount, Transfer};
use minocrab_ledger::stored_cell;
use minocrab_sim::v3::exec::{self, Call};
use minocrab_std::v3::{
    pad32, ts, Bool, Bytes, FieldPath, JubjubPoint, Ledger, LedgerCell, LedgerCounter,
    LedgerHeader, LedgerHistoricMerkleTree, LedgerList, LedgerMap, LedgerMerkleTree, LedgerRepr,
    LedgerSet, Maybe, MerkleTreeDigest, Opaque, Secp256k1Point, StateBuilder, Uint, B32,
};

pub type U64 = Uint<64, Public>;
pub type U8 = Uint<8, Public>;
pub type B32P = B32<Public>;

/// The contract's own address in every executed call.
const ADDRESS: [u8; 32] = [7; 32];

// ---- the two standards ------------------------------------------------------------

/// Magic-only: a Cell at `[0]`.
#[derive(LedgerHeader)]
pub struct Mip0099;

impl LedgerHeader for Mip0099 {
    const MAGIC: [u8; 32] = pad32(b"mip-0099:ledger-header[v1]");
}

/// Magic + version + admin: an Array at `[0]`, the magic at `[0, 0]`, the
/// version at `[0, 1]`, the admin key at `[0, 2]`.
#[derive(LedgerHeader)]
pub struct Versioned {
    pub version: LedgerCell<U8>,
    pub admin: LedgerCell<B32P>,
}

impl LedgerHeader for Versioned {
    const MAGIC: [u8; 32] = pad32(b"mip-0099:versioned-header[v1]");
}

// ---- the generated cases ----------------------------------------------------------

/// Which standard a generated block embeds.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Standard {
    /// [`Mip0099`], declared FIRST in the block.
    Magic,
    /// [`Versioned`], declared LAST in the block.
    Versioned,
}

/// One generated headed block: its `initial_state`, and the paths the derive
/// gave its standard and its three probed body fields (first: a
/// `LedgerCell<U64>`, middle: a `LedgerCounter`, last: a
/// `LedgerMap<U64, U64>`; every other body field a `LedgerCell<U64>`).
pub struct Case {
    pub name: &'static str,
    pub own: usize,
    pub standard: Standard,
    pub initial_state: fn() -> StateBuilder,
    pub magic: FieldPath,
    pub version: Option<FieldPath>,
    pub first: Option<FieldPath>,
    pub middle: Option<FieldPath>,
    pub last: Option<FieldPath>,
}

/// The own-field counts SC-003 names.
const SIZES: [usize; 9] = [0, 1, 14, 15, 16, 30, 211, 225, 226];

/// The magic-first probes of compactc (project 00002 P0b, Probe B) this file
/// has non-headed twins for.
const PROBES: [usize; 2] = [16, 226];

/// The type of own field `k` of `n`, by the probe rule above.
fn body_type(k: usize, n: usize) -> &'static str {
    if k == 0 {
        "LedgerCell<U64>"
    } else if k == n - 1 {
        "LedgerMap<U64, U64>"
    } else if k == n / 2 {
        "LedgerCounter"
    } else {
        "LedgerCell<U64>"
    }
}

/// `ledger_deploy/blocks.rs`, as the generator writes it.
fn blocks_source() -> String {
    let mut out = String::new();
    out.push_str(
        "//! GENERATED by `cargo test -p minocrab-contracts --test ledger_deploy -- --ignored\n\
         //! regenerate_blocks` (the generator is `blocks_source` in `ledger_deploy.rs`) —\n\
         //! do not edit; `the_generated_blocks_are_current` fails when this file is stale.\n\
         //!\n\
         //! T4's headed blocks — every own-field count SC-003 names, each with the\n\
         //! magic-only standard declared FIRST (`H{n}M`) and the multi-field standard\n\
         //! declared LAST (`H{n}V`) — and T4b's non-headed twins of compactc's\n\
         //! magic-first probes (`C{n}`: a `Bytes<32>` magic cell, then `n - 1`\n\
         //! `Uint<64>` cells).\n\
         #![allow(dead_code)]\n\n\
         use minocrab_std::v3::{Ledger, LedgerCell, LedgerCounter, LedgerMap};\n\n\
         use super::{Case, Mip0099, Standard, Versioned, B32P, U64};\n",
    );
    let mut cases = String::new();
    for n in SIZES {
        for standard in [Standard::Magic, Standard::Versioned] {
            let (suffix, std_ty) = match standard {
                Standard::Magic => ("M", "Mip0099"),
                Standard::Versioned => ("V", "Versioned"),
            };
            let name = format!("H{n}{suffix}");
            out.push_str(&format!("\n#[derive(Ledger)]\npub struct {name} {{\n"));
            if standard == Standard::Magic {
                out.push_str(&format!("    pub std: {std_ty},\n"));
            }
            for k in 0..n {
                out.push_str(&format!("    pub f{k}: {},\n", body_type(k, n)));
            }
            if standard == Standard::Versioned {
                out.push_str(&format!("    pub std: {std_ty},\n"));
            }
            out.push_str("}\n");
            let field = |k: usize| format!("Some({name}::new().f{k}.field_path())");
            let first = if n >= 1 { field(0) } else { "None".into() };
            let middle = if n >= 3 { field(n / 2) } else { "None".into() };
            let last = if n >= 2 { field(n - 1) } else { "None".into() };
            let version = match standard {
                Standard::Magic => "None".to_string(),
                Standard::Versioned => format!("Some({name}::new().std.version.field_path())"),
            };
            cases.push_str(&format!(
                "        Case {{\n            name: \"{name}\",\n            own: {n},\n            \
                 standard: Standard::{standard:?},\n            initial_state: {name}::initial_state,\n            \
                 magic: {name}::new().std.magic().field_path(),\n            version: {version},\n            \
                 first: {first},\n            middle: {middle},\n            last: {last},\n        }},\n"
            ));
        }
    }
    out.push_str("\n/// Every generated headed block, in `SIZES` order, `M` before `V`.\n");
    out.push_str("pub fn cases() -> Vec<Case> {\n    vec![\n");
    out.push_str(&cases);
    out.push_str("    ]\n}\n");
    for n in PROBES {
        out.push_str(&format!(
            "\n#[derive(Ledger)]\npub struct C{n} {{\n    pub magic: LedgerCell<B32P>,\n"
        ));
        for k in 1..n {
            out.push_str(&format!("    pub f{k}: LedgerCell<U64>,\n"));
        }
        out.push_str("}\n");
    }
    out
}

fn blocks_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/ledger_deploy/blocks.rs")
}

/// Regenerate `ledger_deploy/blocks.rs` (the house rule: regenerate, never
/// paste).
#[test]
#[ignore = "regenerator: writes tests/ledger_deploy/blocks.rs"]
fn regenerate_blocks() {
    std::fs::write(blocks_path(), blocks_source()).expect("blocks.rs is writable");
}

#[test]
fn the_generated_blocks_are_current() {
    let on_disk = std::fs::read_to_string(blocks_path()).expect("blocks.rs is readable");
    assert!(
        on_disk == blocks_source(),
        "tests/ledger_deploy/blocks.rs is stale: run `cargo test -p minocrab-contracts --test \
         ledger_deploy -- --ignored regenerate_blocks`"
    );
}

// ---- state helpers ------------------------------------------------------------------

type State = StateValue<InMemoryDB>;

/// The node at `path`.
fn at<'a>(state: &'a State, path: &[u8]) -> &'a State {
    let mut node = state;
    for i in path {
        let StateValue::Array(items) = node else {
            panic!("{path:?} walks through a non-Array");
        };
        node = items.get(usize::from(*i)).expect("in range");
    }
    node
}

fn array_len(state: &State) -> usize {
    match state {
        StateValue::Array(items) => items.len(),
        other => panic!("not an Array: {other:?}"),
    }
}

/// Every path at which `a` and `b` differ, walking Arrays of equal length and
/// comparing anything else whole (a Map, a Cell, a tree).
fn diff(a: &State, b: &State) -> Vec<Vec<u8>> {
    fn walk(a: &State, b: &State, path: &mut Vec<u8>, out: &mut Vec<Vec<u8>>) {
        match (a, b) {
            (StateValue::Array(x), StateValue::Array(y)) if x.len() == y.len() => {
                for i in 0..x.len() {
                    path.push(i as u8);
                    walk(
                        x.get(i).expect("in range"),
                        y.get(i).expect("in range"),
                        path,
                        out,
                    );
                    path.pop();
                }
            }
            _ => {
                if a != b {
                    out.push(path.clone());
                }
            }
        }
    }
    let mut out = Vec::new();
    walk(a, b, &mut Vec::new(), &mut out);
    out
}

/// A node's bytes, for "bit-identical".
fn bytes_of(state: &State) -> Vec<u8> {
    let mut bytes = Vec::new();
    midnight_serialize::tagged_serialize(state, &mut bytes).expect("a state value serializes");
    bytes
}

fn u64_cell(v: u64) -> State {
    stored_cell(U64::atoms(), vec![v.to_le_bytes().to_vec()])
}

fn b32_cell(bytes: [u8; 32]) -> State {
    stored_cell(
        vec![AlignmentAtom::Bytes { length: 32 }],
        vec![bytes.to_vec()],
    )
}

/// A one-entry `Map<U64, U64>`.
fn u64_map(key: u64, value: u64) -> State {
    let StateValue::Cell(ref key) = u64_cell(key) else {
        unreachable!()
    };
    StateValue::Map(StorageHashMap::new().insert((**key).clone(), u64_cell(value)))
}

/// The number of root entries compactc gives a block of `n` fields — `n` up
/// to fifteen, one per fifteen-wide segment up to 225, and the segments
/// batched once more past it (determine-ledger-paths.ss `batch`; research
/// midnight-state.md F8).
fn compactc_roots(n: usize) -> usize {
    if n <= 15 {
        n
    } else if n.div_ceil(15) <= 15 {
        n.div_ceil(15)
    } else {
        n.div_ceil(15).div_ceil(15)
    }
}

/// The headed rule, stated on its own terms: compactc's path of body field
/// `k` of `n`, first element + 1.
fn rule_path(n: usize, k: usize) -> Vec<u8> {
    let mut path = FieldPath::in_block(n, k).as_slice().to_vec();
    path[0] += 1;
    path
}

// ---- circuits -------------------------------------------------------------------------

fn compile(body: impl FnOnce(&mut Circuit3)) -> Compiled3 {
    let mut c = Circuit3::new();
    body(&mut c);
    c.finish(false)
}

fn constant(c: &mut Circuit3, v: u64) -> U64 {
    Uint::from_field_unchecked(c.constant(v))
}

/// Run `circuit` against `state` through the executor — whose final step is
/// `QueryContext::query` in verify mode, the ledger's own transcript run.
fn run(circuit: &Compiled3, state: &State) -> State {
    let ctx = exec::context(state.clone(), ADDRESS);
    exec::execute(&circuit.ir, &Call::new(&[], &[]), &ctx)
        .expect("the circuit runs against the deployed state")
        .post
}

// ---- T4 + T9 --------------------------------------------------------------------------

/// T4 and T9 for every generated block.
#[test]
fn t4_every_headed_block_deploys_and_its_writes_land_on_the_rule() {
    let cases = blocks::cases();
    assert_eq!(cases.len(), 2 * SIZES.len());
    for case in cases {
        let name = case.name;
        let n = case.own;
        let built = (case.initial_state)().build();

        // The root: the standard, then compactc's root for the body.
        let root = array_len(&built);
        assert_eq!(root, 1 + compactc_roots(n), "{name}: 1 + R(n)");
        if n == 15 || n == 225 {
            assert_eq!(root, 16, "{name}: the sixteen-entry root");
        }

        // The magic: [0] or [0, 0], one bytes<32> atom, padded back to MAGIC.
        let (magic_path, magic_value): (&[u8], [u8; 32]) = match case.standard {
            Standard::Magic => (&[0], Mip0099::MAGIC),
            Standard::Versioned => (&[0, 0], Versioned::MAGIC),
        };
        assert_eq!(
            case.magic.as_slice(),
            magic_path,
            "{name}: the magic's path"
        );
        let StateValue::Cell(ref magic) = *at(&built, magic_path) else {
            panic!("{name}: the magic is a Cell");
        };
        assert_eq!(
            magic.alignment,
            minocrab::Alignment(vec![minocrab::AlignmentSegment::Atom(
                AlignmentAtom::Bytes { length: 32 }
            )]),
            "{name}: exactly one bytes<32> atom"
        );
        let mut padded = [0u8; 32];
        padded[..magic.value.0[0].0.len()].copy_from_slice(&magic.value.0[0].0);
        assert_eq!(padded, magic_value, "{name}: the magic pads back");
        if case.standard == Standard::Versioned {
            assert_eq!(
                array_len(at(&built, &[0])),
                3,
                "{name}: magic, version, admin"
            );
            assert!(*at(&built, &[0, 1]) == stored_cell(U8::atoms(), U8::default_stored()));
            assert!(*at(&built, &[0, 2]) == b32_cell([0; 32]));
        }

        // The probed body fields: at the rule's paths, at their defaults.
        let probes: [(Option<FieldPath>, usize); 3] = [
            (case.first, 0),
            (case.middle, n / 2),
            (case.last, n.saturating_sub(1)),
        ];
        for (path, k) in probes {
            if let Some(path) = path {
                assert_eq!(path.as_slice(), rule_path(n, k), "{name}: field {k}'s path");
                assert_eq!(
                    usize::from(path.depth()),
                    FieldPath::in_block(n, k).as_slice().len(),
                    "{name}: field {k}'s depth is compactc's"
                );
            }
        }
        if let Some(first) = case.first {
            assert!(
                *at(&built, first.as_slice()) == u64_cell(0),
                "{name}: first at 0"
            );
        }
        if let Some(middle) = case.middle {
            assert!(
                *at(&built, middle.as_slice()) == u64_cell(0),
                "{name}: counter at 0"
            );
        }
        if let Some(last) = case.last {
            assert!(
                matches!(at(&built, last.as_slice()), StateValue::Map(m) if m.is_empty()),
                "{name}: last map empty"
            );
        }

        // The deploy: well formed, applied, stored verbatim.
        let deployed = deploy::deploy(built.clone());
        let pre = deployed.data();
        assert!(
            pre == built,
            "{name}: the ledger stores the state it was given"
        );
        let magic_bytes = bytes_of(at(&pre, magic_path));

        // Each write lands at exactly its path, and the magic is untouched.
        let check = |what: &str, path: FieldPath, circuit: Compiled3, expected: State| {
            let post = run(&circuit, &pre);
            assert_eq!(
                diff(&pre, &post),
                vec![path.as_slice().to_vec()],
                "{name}: {what} moves exactly its own path"
            );
            assert!(
                *at(&post, path.as_slice()) == expected,
                "{name}: {what}'s value"
            );
            assert_eq!(
                bytes_of(at(&post, magic_path)),
                magic_bytes,
                "{name}: {what}: magic bit-identical"
            );
        };
        if let Some(first) = case.first {
            let cell = LedgerCell::<U64>::at_path(first.as_slice());
            let circuit = compile(|c| {
                let v = constant(c, 42);
                cell.write(c, &v);
            });
            check("the first field's Cell write", first, circuit, u64_cell(42));
        }
        if let Some(middle) = case.middle {
            let counter = LedgerCounter::at_path(middle.as_slice());
            let circuit = compile(|c| counter.increment(c, 1));
            check(
                "the middle field's Counter increment",
                middle,
                circuit,
                u64_cell(1),
            );
        }
        if let Some(last) = case.last {
            let map = LedgerMap::<U64, U64>::at_path(last.as_slice());
            let circuit = compile(|c| {
                let (k, v) = (constant(c, 9), constant(c, 7));
                map.insert(c, &k, &v);
            });
            check("the last field's Map insert", last, circuit, u64_map(9, 7));
        }

        // T9: the standard's own field.
        if let Some(version) = case.version {
            assert_eq!(version.as_slice(), &[0, 1], "{name}: the version's path");
            let cell = LedgerCell::<U8>::at_path(version.as_slice());
            let circuit = compile(|c| {
                let v: U8 = Uint::from_field_unchecked(c.constant(3u64));
                cell.write(c, &v);
            });
            let three = stored_cell(U8::atoms(), vec![vec![3]]);
            check("the standard's version write", version, circuit, three);
        }
    }
}

// ---- the composite slots' shares --------------------------------------------------------

/// The README treasury with a standard: the Signet's five fields at
/// `[1]..[5]` (the sealed signer Null until the deployer sets it, the MPC key
/// at its identity), the Pending's two maps at `[6]`, `[7]`.
#[derive(Ledger)]
struct HeadedTreasury {
    signet: Signet,
    std: Mip0099,
    transfers: Pending<Transfer, Owned<Amount>, 2>,
}

/// A standard first, then a Signet and an Outbox: the Outbox's Pending maps
/// and its stream's five fields after the Signet's.
#[derive(Ledger)]
struct HeadedOutbox {
    std: Mip0099,
    signet: Signet,
    calls: Outbox<Transfer, HandleOwned<Amount>, 2>,
}

#[test]
fn composite_slots_contribute_their_members_and_deploy() {
    let secp = stored_cell(
        Secp256k1Point::<Public>::atoms(),
        Secp256k1Point::<Public>::default_stored(),
    );
    let signer = b32_cell([0x5a; 32]);

    let block = HeadedTreasury::new();
    let mut state = HeadedTreasury::initial_state();
    assert!(
        *state
            .get(block.signet.signer.field_path())
            .expect("declared")
            == StateValue::Null
    );
    state.set(block.signet.signer.field_path(), signer.clone());
    let built = state.build();
    assert_eq!(array_len(&built), 8);
    assert!(*at(&built, &[0]) == b32_cell(Mip0099::MAGIC));
    assert!(*at(&built, &[1]) == signer, "the sealed signer, as set");
    assert!(
        *at(&built, &[2]) == secp,
        "the MPC key at the point's identity"
    );
    assert!(*at(&built, &[3]) == u64_cell(0), "the request nonce");
    assert!(*at(&built, &[4]) == b32_cell([0; 32]), "caip2");
    assert!(*at(&built, &[5]) == u64_cell(0), "the chain id");
    assert_eq!(block.transfers.record_path().as_slice(), &[6]);
    for i in [6, 7] {
        assert!(
            matches!(at(&built, &[i]), StateValue::Map(m) if m.is_empty()),
            "[{i}]"
        );
    }
    assert!(deploy::deploy(built.clone()).data() == built);

    let built = HeadedOutbox::initial_state().build();
    assert_eq!(array_len(&built), 1 + 5 + 7, "standard, signet, outbox");
    assert!(*at(&built, &[2]) == secp);
    for (i, map) in [
        (6, true),
        (7, true),
        (8, true),
        (9, false),
        (10, false),
        (11, true),
        (12, true),
    ] {
        if map {
            assert!(
                matches!(at(&built, &[i]), StateValue::Map(m) if m.is_empty()),
                "[{i}] a map"
            );
        } else {
            assert!(
                *at(&built, &[i]) == u64_cell(0),
                "[{i}] an accumulator cell at 0"
            );
        }
    }
    assert!(deploy::deploy(built.clone()).data() == built);
}

// ---- T4b: compactc's generated initialState, byte for byte -----------------------------

/// A fixture's bytes: the hex after its `#` provenance lines.
fn oracle(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/initial_state")
        .join(format!("{name}.state.hex"));
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let hex: String = text
        .lines()
        .filter(|line| !line.starts_with('#'))
        .flat_map(|line| line.trim().chars())
        .collect();
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex"))
        .collect()
}

fn assert_oracle(name: &str, state: State) {
    let ours = deploy::data_only_bytes(state.clone());
    let theirs = oracle(name);
    assert!(
        ours == theirs,
        "{name}: minocrab's initial state serializes to {} bytes, compactc's to {}\n\
         ours:   {}\ntheirs: {}\nstate: {state:?}",
        ours.len(),
        theirs.len(),
        ours.iter().map(|b| format!("{b:02x}")).collect::<String>(),
        theirs
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>(),
    );
    // …and compactc's state is one the ledger deploys.
    assert!(deploy::deploy(state.clone()).data() == state);
}

/// A two-atom record, Compact's `struct Pair { a: Uint<16>; b: Bytes<3>; }`.
#[derive(minocrab_std::v3::LedgerRepr)]
struct Pair {
    a: Uint<16, Public>,
    b: Bytes<3, Public>,
}

/// `e_adts.compact`'s fifteen fields, one of every kind.
#[derive(Ledger)]
struct EAdts {
    b32: LedgerCell<B32P>,
    num: LedgerCell<U64>,
    flag: LedgerCell<Bool<Public>>,
    digest: LedgerCell<MerkleTreeDigest<Public>>,
    name: LedgerCell<Opaque<ts::Str, Public>>,
    maybe: LedgerCell<Maybe<B32P, Public>>,
    secp: LedgerCell<Secp256k1Point<Public>>,
    jub: LedgerCell<JubjubPoint<Public>>,
    pair: LedgerCell<Pair>,
    count: LedgerCounter,
    m: LedgerMap<B32P, U64>,
    s: LedgerSet<B32P>,
    l: LedgerList<U64>,
    mt: LedgerMerkleTree<10, B32P>,
    hmt: LedgerHistoricMerkleTree<10, B32P>,
}

/// One field of every ledger type — the curve points at their identities,
/// the HistoricMerkleTree with its blank root in the history.
#[test]
fn t4b_every_ledger_type_is_compactcs_initial_state() {
    assert_oracle("e_adts", EAdts::initial_state().build());
}

/// The shipped `Adts` contract (its committed compactc fixture, `adts/out`).
#[test]
fn t4b_the_adts_contract_is_compactcs_initial_state() {
    assert_oracle(
        "adts",
        minocrab_contracts::adts::Adts::initial_state().build(),
    );
}

/// The magic-first probes: compactc's constructor writes
/// `pad(32, "mip-0099:ledger-header[v1]")` at `[0, 0]` / `[0, 0, 0]`, the
/// deployer's `set` does the same, and the segmented skeletons agree.
#[test]
fn t4b_the_magic_first_probes_are_compactcs_initial_state() {
    let magic = b32_cell(Mip0099::MAGIC);

    let mut state = blocks::C16::initial_state();
    state.set(blocks::C16::new().magic.field_path(), magic.clone());
    assert_eq!(blocks::C16::new().magic.field_path().as_slice(), &[0, 0]);
    assert_oracle("b_n16", state.build());

    let mut state = blocks::C226::initial_state();
    state.set(blocks::C226::new().magic.field_path(), magic);
    assert_eq!(
        blocks::C226::new().magic.field_path().as_slice(),
        &[0, 0, 0]
    );
    assert_oracle("b_n226", state.build());
}
